# FlatOut Music Shuffler by Chloe @gaycoderprincess
# enjoy, nya~ :3

[main]
sequential = false			# Plays songs sequentially in the playlist order (this is the vanilla behavior)
async = true				# Loads the next song on a separate thread (might be unstable, disable if you're getting crashes!)